# Generated by Django 3.2.3 on 2021-08-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='star',
            field=models.IntegerField(default=0),
        ),
    ]
