# Generated by Django 3.2.3 on 2021-08-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0002_bookmark_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
