# Generated by Django 3.2.3 on 2021-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0003_bookmark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(null=True, upload_to='appname'),
        ),
    ]
