# Generated by Django 3.2.3 on 2021-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awapp', '0005_alter_bookmark_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
